[workstations]

; ===== АУДИТОРИЯ 101 =====
[room_101]
pc01 ansible_host=10.10.1.118
pc02 ansible_host=10.10.1.119
pc03 ansible_host=10.10.1.121
pc04 ansible_host=10.10.1.117

; ===== АУДИТОРИЯ 102 =====
[room_102]
pc05 ansible_host=10.10.1.115
pc06 ansible_host=10.10.1.120
pc07 ansible_host=10.10.1.129

; ===== АУДИТОРИЯ 103 =====
[room_103]
pc08 ansible_host=10.10.1.154
pc09 ansible_host=10.10.1.116
pc10 ansible_host=10.10.1.113

; ===== АУДИТОРИЯ 104 =====
[room_104]
pc11 ansible_host=10.10.1.114
pc12 ansible_host=10.10.1.112
pc13 ansible_host=10.10.1.111


; ===== ОБЩАЯ ГРУППА ВСЕХ ПК =====
[all_workstations:children]
room_101
room_102
room_103
room_104


; ===== ТЕХНИКУМ =====
[techschool:children]
all_workstations


; ===== ОБЩИЕ ПАРАМЕТРЫ =====
[techschool:vars]
ansible_user=admin
ansible_become=true
ansible_become_method=sudo