---
- name: Настройка часового пояса
  timezone:
    name: Europe/Moscow

- name: Установка базовых утилит
  package:
    name:
      - htop
      - wget
      - curl
      - net-tools
    state: present